const users = require('./users/users.service.js');
const groups = require('./groups/groups.service.js');
const roles = require('./roles/roles.service.js');
const projects = require('./projects/projects.service.js');
const teams = require('./teams/teams.service.js');
const organizations = require('./organizations/organizations.service.js');
const groupRoles = require('./group-roles/group-roles.service.js');
const teamMembers = require('./team-members/team-members.service.js');
const blocks = require('./blocks/blocks.service.js');
const blockVariables = require('./block-variables/block-variables.service.js');
const resources = require('./resources/resources.service.js');
const stacks = require('./stacks/stacks.service.js');
const syslog = require('./syslog/syslog.service.js');
const resourceLogs = require('./resource-logs/resource-logs.service.js');
const userRoles = require('./user-roles/user-roles.service.js');
const customIcons = require('./custom-icons/custom-icons.service.js');
const workflows = require('./workflows/workflows.service.js');
const workflowActivities = require('./workflow-activities/workflow-activities.service.js');
const requests = require('./requests/requests.service.js');
const requestActivities = require('./request-activities/request-activities.service.js');
const requestTaskQueue = require('./request-task-queue/request-task-queue.service.js');
const blockTypes = require('./block-types/block-types.service.js');
const recordVersions = require('./record-versions/record-versions.service.js');
const recordDeletions = require('./record-deletions/record-deletions.service.js');
const workflowBlockVariables = require('./workflow-block-variables/workflow-block-variables.service.js');
const workflowBlocks = require('./workflow-blocks/workflow-blocks.service.js');
// eslint-disable-next-line no-unused-vars
module.exports = function (app) {
  app.configure(users);
  app.configure(groups);
  app.configure(roles);
  app.configure(projects);
  app.configure(teams);
  app.configure(organizations);
  app.configure(groupRoles);
  app.configure(teamMembers);
  app.configure(blocks);
  app.configure(blockVariables);
  app.configure(resources);
  app.configure(stacks);
  app.configure(syslog);
  app.configure(resourceLogs);
  app.configure(userRoles);
  app.configure(customIcons);
  app.configure(workflows);
  app.configure(workflowActivities);
  app.configure(requests);
  app.configure(requestActivities);
  app.configure(requestTaskQueue);
  app.configure(blockTypes);
  app.configure(recordVersions);
  app.configure(recordDeletions);
  app.configure(workflowBlockVariables);
  app.configure(workflowBlocks);
};
